/*
SET 9
Create the database EXAM and create given tables with all necessary constraints such as
primary key, foreign key, unique key, not null and check constraints.

APPLICANT (AID, ANAME, ADDR, ABIRTH_DT)

ENTRANCE_TEST (ETID, ETNAME, MAX_SCORE, CUT_SCORE)

ETEST_CENTRE (ETCID, LOCATION, INCHARGE, CAPACITY)

ETEST_DETAILS (AID, ETID, ETCID, ETEST_DT, SCORE)
*/

CREATE TABLE APPLICANT 
(AID  VARCHAR2(5) CHECK(AID LIKE 'A%'),
ANAME VARCHAR(10),
ADDR VARCHAR(10),
ABIRTH_DT DATE,
PRIMARY KEY(AID)
);

INSERT INTO APPLICANT VALUES('A101','MR.A','JAMNAGAR','18-OCT-1999');
INSERT INTO APPLICANT VALUES('A102','MR.B','RAJKOT','15-JAN-2000');
INSERT INTO APPLICANT VALUES('A103','MRS.C','JAMNAGAR','1-JAN-1998');
INSERT INTO APPLICANT VALUES('A104','MR.D','RAJKOT','5-JUN-1997');
INSERT INTO APPLICANT VALUES('A105','MRS.E','JAMNAGAR','18-OCT-2000');


CREATE TABLE ENTRANCE_TEST
(ETID INT PRIMARY KEY,
ETNAME VARCHAR(10), 
MAX_SCORE NUMBER(5) CHECK(MAX_SCORE>0 AND MAX_SCORE<=100), 
CUT_SCORE NUMBER(5) CHECK(CUT_SCORE>0 AND CUT_SCORE<=100));

INSERT INTO ENTRANCE_TEST VALUES(1,'ORACLE',100,35);
INSERT INTO ENTRANCE_TEST VALUES(2,'.NET',100,40);
INSERT INTO ENTRANCE_TEST VALUES(3,'PHP',100,35);
INSERT INTO ENTRANCE_TEST VALUES(4,'WORDPRESS',100,45);
INSERT INTO ENTRANCE_TEST VALUES(5,'NETWORKING',100,35);


/*INSERT INTO ENTRANCE_TEST VALUES(1,'CMAT',100,50);
INSERT INTO ENTRANCE_TEST VALUES(2,'ORACLE',100,85);   
INSERT INTO ENTRANCE_TEST VALUES(3,'NEET',100,40);
INSERT INTO ENTRANCE_TEST VALUES(4,'JEE',100,50);
INSERT INTO ENTRANCE_TEST VALUES(5,'TAT',100,30);
INSERT INTO ENTRANCE_TEST VALUES(6,'STAT',100,40);
INSERT INTO ENTRANCE_TEST VALUES(7,'STAT',100,50);
INSERT INTO ENTRANCE_TEST VALUES(8,'QTAT',100,65);*/


CREATE TABLE ETEST_CENTRE 
(ETCID INT PRIMARY KEY, 
LOCATION VARCHAR(10), 
INCHARGE VARCHAR(10), 
CAPACITY NUMBER(5) CHECK(CAPACITY>0 AND CAPACITY<=50)
);

	INSERT INTO ETEST_CENTRE VALUES(1,'JAM','INC.A',25);
	INSERT INTO ETEST_CENTRE VALUES(2,'RAJ','INC.B',40);
	INSERT INTO ETEST_CENTRE VALUES(3,'AHM','INC.C',20);
	INSERT INTO ETEST_CENTRE VALUES(4,'JAM','INC.D',45);
	INSERT INTO ETEST_CENTRE VALUES(5,'RAJ','INC.E',30);

/*INSERT INTO ETEST_CENTRE VALUES(1,'JAM','IS',100);
INSERT INTO ETEST_CENTRE VALUES(2,'RAJ','ISP',80);
INSERT INTO ETEST_CENTRE VALUES(3,'POR','IP',60);
INSERT INTO ETEST_CENTRE VALUES(4,'JUN','PS',40);
INSERT INTO ETEST_CENTRE VALUES(5,'DHR','PI',20);
INSERT INTO ETEST_CENTRE VALUES(6,'DHRR','SPI',20);*/

CREATE TABLE ETEST_DETAILS 
(AID  VARCHAR2(5) REFERENCES APPLICANT(AID), 
ETID INT REFERENCES ENTRANCE_TEST(ETID), 
ETCID INT REFERENCES ETEST_CENTRE, 
ETEST_DT DATE, 
SCORE NUMBER(5) CHECK (SCORE BETWEEN 0 AND 100)
);

INSERT INTO ETEST_DETAILS VALUES('A101',1,1,'16-OCT-16',60);
INSERT INTO ETEST_DETAILS VALUES('A102',2,3,'18-OCT-16',70);
INSERT INTO ETEST_DETAILS VALUES('A103',2,1,'16-NOV-16',60);
INSERT INTO ETEST_DETAILS VALUES('A104',1,4,'16-DEC-16',75);
INSERT INTO ETEST_DETAILS VALUES('A105',3,5,'16-JUN-16',55);


/*INSERT INTO ETEST_DETAILS VALUES('A111',1,1,'10-NOV-21',380);
INSERT INTO ETEST_DETAILS VALUES('A123',2,2,'10-NOV-21',380);
INSERT INTO ETEST_DETAILS VALUES('A124',3,3,'10-NOV-21',380);
INSERT INTO ETEST_DETAILS VALUES('A222',4,4,'10-NOV-21',380);
INSERT INTO ETEST_DETAILS VALUES('A223',5,5,'10-NOV-21',380);
INSERT INTO ETEST_DETAILS VALUES('A567',6,6,'10-NOV-21',380);
INSERT INTO ETEST_DETAILS VALUES('A567',7,6,'10-NOV-21',380);
INSERT INTO ETEST_DETAILS VALUES('A567',8,6,'10-NOV-21',380);*/
--https://github.com//Ravan24

select * from APPLICANT;
select * from ENTRANCE_TEST;
select * from ETEST_CENTRE;
select * from ETEST_DETAILS;

delete from ETEST_DETAILS;
delete from ETEST_CENTRE;
delete from ENTRANCE_TEST;
delete from APPLICANT;



/*1. Modify the APPLICANT table so that every applicant id has an ‘A’ before its
value. E.g. if value is ‘1123’, it should become ‘A1123’.
Display test center details where no tests were conducted.
Display details about applicants who have the same score as that of Ajaykumar in
‘ORACLE FUNDAMENTALS’.*/.

alter table APPLICANT  ADD Check (AID like '%A');

--2. Display details of applicants who appeared for all tests

		select * from APPLICANT where AID in(
		select distinct AID from ETEST_DETAILS
		WHERE
		aid in (select aid from ETEST_DETAILS group by aid having 
		count(ETID)=(select count(*) from ENTRANCE_TEST))
		and ETID in (select distinct ETID from ENTRANCE_TEST));

		select aid,count(ETID) from ETEST_DETAILS group by aid;

		select aid from ETEST_DETAILS group by aid having count (ETID)=3;

		--or

		select * from APPLICANT where AID in(
		select distinct AID from ETEST_DETAILS
		WHERE
		aid in (select aid from ETEST_DETAILS group by aid having 
		count(ETID)=(select count(*) from ENTRANCE_TEST)));

--3. Display those tests where no applicant has failed
	
		SELECT AID FROM ETEST_DETAILS  WHERE ETID IN (SELECT ETID FROM ETEST_DETAILS);
	
		SELECT A.AID,A.ANAME,E.ETID,E.ETNAME,D.SCORE
		FROM APPLICANT A,ENTRANCE_TEST E,ETEST_DETAILS D
		WHERE A.AID=D.AID AND E.ETID=D.ETID AND D.SCORE>=60;

/*4. Display details of entrance test centers which had full attendance between 1st Oct 15
	and 15th Oct 16.*/

		SELECT * FROM ETEST_DETAILS WHERE ETEST_DT BETWEEN TO_DATE('16-OCT-16','DD-MON-YY')
		AND TO_DATE('16-NOV-16','DD-MON-YY');

		SELECT EC.ETCID FROM ETEST_CENTRE EC 
		WHERE (EC.ETCID,EC.CAPACITY) IN 
		(SELECT EC.ETCID,EC.CAPACITY FROM ETEST_DETAILS WHERE ETEST_DT BETWEEN TO_DATE('16-OCT-16','DD-MON-YY')
		AND TO_DATE('16-NOV-16','DD-MON-YY'));

/*5.Display details of the applicants who scored more than the cut score in the tests they
appeared in.*/

		SELECT A.AID,A.ANAME,E.ETID,E.ETNAME,E.CUT_SCORE,ED.SCORE
		FROM APPLICANT A,ENTRANCE_TEST E,ETEST_DETAILS ED
		WHERE
		A.AID=ED.AID AND E.ETID=ED.ETID AND ED.SCORE>E.CUT_SCORE;


--6. Display average and maximum score test wise of tests conducted at Mumbai.
	
	SELECT * FROM ETEST_CENTRE WHERE LOCATION='AHM';

		SELECT AVG(SCORE) FROM ETEST_DETAILS;
		SELECT MAX(SCORE) FROM ETEST_DETAILS;

		SELECT * FROM ETEST_DETAILS;

		SELECT * FROM ENTRANCE_TEST ORDER BY ETNAME;

		SELECT ET.ETID,ET.ETNAME,EC.ETCID,EC.LOCATION,ED.SCORE
		FROM ETEST_CENTRE EC,ENTRANCE_TEST ET,ETEST_DETAILS ED
		WHERE ET.ETID=ED.ETID AND EC.ETCID=ED.ETCID AND EC.LOCATION='JAM'ORDER BY ET.ETNAME;
	

		SELECT ET.ETID,MAX(ED.SCORE),avg(ED.SCORE)
		FROM ETEST_CENTRE EC,ENTRANCE_TEST ET,ETEST_DETAILS ED
		WHERE ET.ETID=ED.ETID AND EC.ETCID=ED.ETCID AND EC.LOCATION='JAM' group BY ET.ETID;
	
--7. Display the number of applicants who have appeared for each test, test center wise.*/
	
	SELECT COUNT(AID) FROM ETEST_DETAILS;
	
	SELECT ETID,ETCID,COUNT(AID) FROM ETEST_DETAILS
	GROUP BY ETID,ETCID ORDER BY ETID;


-- 8. Display details about test centers where no tests have been conducted.
	
	SELECT * FROM ETEST_CENTRE;
	SELECT * FROM ETEST_DETAILS;
 
	SELECT * FROM ETEST_CENTRE 
	WHERE 
	ETCID NOT IN (SELECT ETCID FROM ETEST_DETAILS);

/* 9. For tests, which have been conducted between 2-3-17 and 23-4-17, show details of
	  the tests as well as the test centre. */
	

	SELECT * FROM ETEST_DETAILS WHERE ETEST_DT BETWEEN TO_DATE('16-JUN-16','DD-MON-YY')
	AND TO_DATE('18-OCT-16','DD-MON-YY');


	SELECT ET.ETID,ET.ETNAME,
	EC.ETCID,EC.LOCATION,EC.INCHARGE,
	ED.ETID,ED.ETEST_DT,ED.SCORE
	FROM ENTRANCE_TEST ET,ETEST_CENTRE EC,ETEST_DETAILS ED
	WHERE ET.ETID=ED.ETID AND EC.ETCID=ED.ETCID 
	AND ETEST_DT BETWEEN TO_DATE('16-JUN-16','DD-MON-YY')
	AND TO_DATE('18-OCT-16','DD-MON-YY');

/*10.How many applicants appeared in the ‘ORACLE FUNDAMENTALS’ test at
Chennai in the month of February?*/

 SELECT * FROM ENTRANCE_TEST WHERE ETNAME='ORACLE';
 SELECT * FROM ETEST_CENTRE WHERE LOCATION='AHM';
 SELECT * FROM ETEST_DETAILS WHERE TO_CHAR (ETEST_DT,'MON')='NOV';

 SELECT A.AID,A.ANAME,
 ET.ETID,ET.ETNAME,
 EC.ETCID,EC.LOCATION,
 ED.ETEST_DT
 FROM APPLICANT A,ENTRANCE_TEST ET,ETEST_CENTRE EC,ETEST_DETAILS ED 
 WHERE
 A.AID=ED.AID AND ET.ETID=ED.ETID AND EC.ETCID=ED.ETCID 
 AND ET.ETNAME='ORACLE' AND EC.LOCATION='AHM' AND TO_CHAR (ED.ETEST_DT,'MON')='OCT';

/*11.Display details about applicants who appeared for tests in the same month as the
month in which they were born.*/

SELECT A.AID,A.ANAME,A.ABIRTH_DT,
ED.AID,ED.ETEST_DT
FROM APPLICANT A,ETEST_DETAILS ED
WHERE A.AID=ED.AID AND TO_CHAR(ABIRTH_DT,'MON')=TO_CHAR(ETEST_DT,'MON') ;

 

/*12.Display the details about APPLICANTS who have scored the highest in each test,
test centre wise.*/

	SELECT ED.ETID,ED.ETCID,MAX(SCORE) FROM ETEST_DETAILS ED
	GROUP BY ED.ETID,ED.ETCID ORDER BY ETID;

	SELECT A.AID,ED.ETID,ED.ETCID,MAX(SCORE) 
	FROM ETEST_DETAILS ED,APPLICANT A WHERE A.AID=ED.AID
	GROUP BY A.AID,ED.ETID,ED.ETCID ORDER BY ED.ETID;

	SELECT MAX(SCORE) FROM ETEST_DETAILS;
	
---
